version: '3'

services:
  nginx-rtmp:
    build: .  # Usar o Dockerfile local
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./streamRIP:/usr/share/nginx/streamRIP
      - ./videos:/videos
    restart: unless-stopped