version: '3'
services:
  nginx-rtmp:
    build: .  # Usar o Dockerfile local
    ports:
      - "1935:1935"  # RTMP
      - "8080:80"    # HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./streamRIP:/usr/share/nginx/streamRIP
      - ./videos:/videos
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    command: >
      bash -c "chmod +x /usr/share/nginx/streamRIP/*.sh &&
              /usr/share/nginx/streamRIP/nginx_start.sh &
              nginx -g 'daemon off;'"

#./usr/share/nginx/streamRIP/switch.sh stream2